### ISSUE TITLE
Update the Deployment documentation

### ISSUE THREAD

**Issue by haacked** [octokit/octokit.net#993]
Now that we're moving to AppVeyor, we should try and get NuGet package deployment from AppVeyor working when we tag a `release` branch and then update this doc: https://github.com/octokit/octokit.net/blob/master/DEPLOYMENT.md

**Comment by shiftkey** [comment]
I had some luck with this on an old project - this is the current AppVeyor config we're using to deploy to GitHub Releases and Chocolatey:

> https://github.com/Code52/carnac/blob/master/appveyor.yml#L22-L37

**Comment by Haacked** [comment]
Does that deploy NuGet packages on every merge to master? I'd like to avoid that. I was trying to set it up so it would only deploy from a branch named "`release`" when we tag that release.

**Comment by shiftkey** [comment]
Oh yes, I was totally lazy and made it deploy whenever `master` is updated.

How I created that file was roughly like this: 
 - get the configuration setup right in the admin portal
 - generate the right `appveyor.yml` config file through the portal (sensitive values get encrypted)
 - add that to source control

**Comment by alfhenrik** [comment]
According to [this](http://www.appveyor.com/docs/branches#conditional-build-configuration) you can specify conditional build configurations depending on branches

**Comment by Haacked** [comment]
@alfhenrik Yeah. Further down on that page, you can also Build on Tags (GitHub only). I set that up in our appveyor, but it didn't seem to work. However, it's possible I did something wrong.

**Comment by alfhenrik** [comment]
:cold_sweat: that took a lot more effort than I expected, but I finally got it working by adding the below to `appveyor.yml`

```
deploy:
- provider: NuGet
  server: <yournugetfeed> # Remove to push to NuGet.org
  api_key:
    secure: <secureapikeyfromappveyor>
  skip_symbols: true
  artifact: /octokit.*\.nupkg/
  on:
    branch: release
    APPVEYOR_REPO_TAG: true
```

**Comment by shiftkey** [comment]
This is something I'll be looking at next week. Thanks @alfhenrik for that extra info.

**Comment by alfhenrik** [comment]
![](http://www.reactiongifs.com/wp-content/uploads/2013/05/kramer-yeah.gif)

:rocket: :fireworks: :tada: :confetti_ball: 

The below works a treat
```
init:
  - git config --global core.autocrlf input
build_script:
  - cmd: build.cmd BuildApp
  - cmd: build.cmd UnitTests
  - cmd: build.cmd ConventionTests
  - cmd: build.cmd CreatePackages
test: off
nuget:
  account_feed: true
  project_feed: true
artifacts:
- path: 'packaging\octokit*.nupkg'
  name: OctokitPackages
deploy:
- provider: NuGet
  server: 
  api_key:
    secure: 
  skip_symbols: true
  artifact: OctokitPackages
  on:
    branch: release
    APPVEYOR_REPO_TAG: true
```
